# All env variables that are used in one place
# This is for deployment-specific values, which may be managed by other teams

env:
  tracing:
    exportEnabled: ${CLOUD_TRACE_ENABLED:false}
    samplingRate: ${SAMPLING_PROBABILITY:0}
  sam:
    basePath: ${SAM_ADDRESS:https://sam.dsde-dev.broadinstitute.org}

# Below here is non-deployment-specific

# When the target is 'local' the write-config.sh script will generate this properties file. It
# contains the configuration of the BPM test application. We can use that application in our
# integration testing to make sure the application code paths are working. However, we do not
# want it to appear in production environments.
spring.config.import: optional:file:../config/local-properties.yml;classpath:git.properties

logging.pattern.level: '%X{requestId} %5p'

server:
  max-http-header-size: 32KB
  compression:
    enabled: true
    mimeTypes: text/css,application/javascript
  port: 8080

spring:
  # application name and version are used to populate the logging serviceContext
  # https://github.com/DataBiosphere/terra-common-lib/blob/480ab3daae282ddff0fef8dc329494a4422e32f1/src/main/java/bio/terra/common/logging/GoogleJsonLayout.java#L118
  application.name: iffy
  application.version: ${iffy.version.gitHash:unknown}

  web:
    resources:
      cache:
        cachecontrol:
          maxAge: 0
          mustRevalidate: true
        useLastModified: false
      staticLocations: classpath:/api/

management:
  server:
    port: 9098
  endpoints:
    web:
      exposure:
        include: "*"

iffy:
  ingress:
    # Default value that's overridden by Helm.
    domainName: localhost:8080

  status-check:
    enabled: true
    pollingIntervalSeconds: 60
    startupWaitSeconds: 5
    stalenessThresholdSeconds: 125

  sam:
    basePath: ${env.sam.basePath}

terra.common:
  kubernetes:
    inKubernetes: false

  tracing:
    sampling-ratio: ${env.tracing.samplingRate}
  google:
    tracing:
      enabled: ${env.tracing.exportEnabled}

otel:
  sdk:
    disabled: false # set to true to disable all open telemetry features

  springboot:
    resource:
      attributes:
        service:
          name: ${spring.application.name}
          version: ${iffy.version.gitTag:unknown}
