openapi: 3.0.3
info:
  title: Evaluation Contexts
  description: Contains evaluation context schemas for Terra feature flags
  version: 0.0.1
paths: {}
components:
  schemas:
    UserV1Context:
      x-is-evaluation-context: true
      x-schema-kind: "user"
      x-schema-version: "v1"
      description: Evaluation context for a Terra user (V1)
      type: object
      required: [ email, id ]
      properties:
        id:
          type: string
          description: User ID for the Terra user
          example: TODO
        email:
          type: string
          description: Email address for the Terra user
          example: b.adm@gmail.com

    SystemV1Context:
      x-is-evaluation-context: true
      x-schema-kind: "system"
      x-schema-version: "v1"
      description: Evaluation context providing information about the calling system
      type: object
      required: [ environment.name, environment.type, service.name, service.version ]
      properties:
        environment:
          type: object
          description: Contains information about the runtime environment of the client
          properties:
            name:
              type: string
              description: Name of the Terra environment where the client is running
              example: "dev"
            type:
              type: string
              description: Type of the Terra environment.
              enum: [ "local", "bee", "live" ]
        service:
          type: object
          description: Contains information about the service that is running the client
          properties:
            name:
              type: string
              description: Name of the Terra service where the client is running
              example: "cbas"
            version:
              type: string
              description: Version of the service that is running the client
              example: "1.2.3"

    CustomV1Context:
      x-is-evaluation-context: true
      x-schema-kind: "custom"
      x-schema-version: "v1"
      description: Evaluation context providing information about the calling system
      type: object
      required: [ targetingKey ]
      additionalProperties: true
      properties:
        targetingKey:
          type: string
          description: Targeting key to be used for percentage rollouts and caching evaluations
          example: "some-unique-identifier"
